### ISSUE TITLE
Dude just forking not creating. He is not ok

### ISSUE THREAD

**Issue by McProgrammerX** [Realhack1/My-story#2]

**Comment by Realhack1** [comment]
what i do

**Comment by Realhack1** [comment]
heres my website for proof https://gamingfun.me/WX7F5U

**Comment by McProgrammerX** [comment]
But all the links are copied from someone else, and I also saw you leak the email of a persons school email. Also I understand you are trying to make new bypasses so people can play games unrestricted but you can just learn how to do that on YouTube or learn it from Google, then tell people how to use the bypass and also it is ok for you to fork it but you don't really say who the original creator & author is. Plus do you know you can make cheats to bypass school restrictions, Dude just learn programming.

**Comment by McProgrammerX** [comment]
Imma about this man's whole career:

You know how I play Roblox I use Now.gg and with Now.gg you can play alot of game, including Roblox all in the browser

**Comment by Realhack1** [comment]
Now.gg blocked and you can't play roblox with a VPN or proxy And trickjoker312 I gave credit before I stoped copying him and his email was on his profile I just did a method of research

**Comment by McProgrammerX** [comment]
ok dude

**Comment by McProgrammerX** [comment]
I believe you
